### ISSUE TITLE
注册有代表性的域名

### ISSUE THREAD

**Issue by kitewu** [kfcoding/gitcourse#10]
例如 gitcourse.io

**Comment by kitewu** [comment]
目前 gitcourse.io 可以注册

![image](https://user-images.githubusercontent.com/16188599/66794075-a492d400-ef32-11e9-9dc0-233a7899932d.png)

**Comment by jizusun** [comment]
感觉 gitcourse 这个名字不太容易搜到哎

https://www.google.com/search?q=GitCourse

**Comment by frank-zsy** [comment]
> 感觉 gitcourse 这个名字不太容易搜到哎
> 
> https://www.google.com/search?q=GitCourse

这个是不是 SEO 的问题，我们是不是要刻意做一下 SEO？

**Comment by kitewu** [comment]
是的，现在google和百度都搜不到
