### ISSUE TITLE
lookbehind is not supported by IE,Edge and Safari

### ISSUE THREAD

**Issue by deplay** [kfcoding/gitcourse#45]
环境
操作系统：Ubuntu18.04
浏览器：Firefox Quantum 68.0.1 64位
Issue类型：Bug

描述：
使用Ubuntu18.04系统按https://github.com/kfcoding/gitcourse 所提供的步骤启动服务器后，使用Firefox quantum 68.0.1 64位访问http://localhost:3000/ 发生错误，如下图所示。
<img width="506" alt="pic1" src="https://s2.ax1x.com/2019/12/08/QdEOxA.png">
报错原因来自index.js，这是由webpack打包而成的，更具体的错误原因来自gitcourse/src/store/Scenario.js 的第53行 var matches = extraTab.match(/(?<=\[:).+?(?=])/mg); 。
在该行代码中使用了js正则中的lookbehind 断言机制（即 ?<= ），但该机制在Firefox中并未实现，其对应的官方issue至今仍是open状态， https://bugzilla.mozilla.org/show_bug.cgi?id=1225665
<img width="337" alt="pic2" src="https://s2.ax1x.com/2019/12/08/QdEq8H.png">
更进一步，据https://caniuse.com/#feat=mdn-javascript_builtins_regexp_lookbehind_assertion 提供的数据
<img width="878" alt="pic3" src="https://s2.ax1x.com/2019/12/08/QdEvrt.png">
该特性在全球浏览器中的支持度仅为67.8%，尤其是IE，Edge，Safari对该功能均不支持。该bug对kfcoding的潜在用户（即高校师生）会造成很大的影响，主要有两个原因：1.高校为了正常使用一些老旧系统，还在使用IE浏览器2.学生自行购置的windows笔记本一般预装Edge，Macbook和iPad等则使用Safari。
经我搜索，lookbehind断言在源码中只使用了一次，直接修复即可，并注意在以后的开发中不再使用或引入相应的polyfill。一种可行的修改方案是把gitcourse/src/store/Scenario.js 的第53行到56行的如下代码，仅供参考。
var matches = extraTab.match(/(?<=\[:).+?(?=])/mg);
if (matches && matches.length > 0){
exposed_ports[`${matches[0]}/tcp`]={}
}
改为
var matches = extraTab.match(/(\[:).+?(?=])/mg);
if (matches && matches.length > 0){
matches[0]=matches[0].replace(/(\[:)/mg,'');
exposed_ports[`${matches[0]}/tcp`]={}
}

**Comment by LiuChangFreeman** [comment]
将采用您的修复建议

**Comment by will-ww** [comment]
能否用PR的形式来进行合并~

**Comment by deplay** [comment]
我建议还是由开发团队处理此issue并确定具体修复方案，因为

1. 按我的方案修改代码后，在Ubuntu18.04Firefox Quantum 68.0.1 64位下仍有其他报错（应该不是因我的修改而产生的）需要处理，所以我建议开发团队使用我所述的环境跑一遍系统，处理了所有问题后，一次性提交代码。

2.  该系统开源出来的部分并未包含自动化测试，所以我不能确定按我的方案修改后，该系统（而不仅是首页）的所有页面，所有功能是否和预期一致。

**Comment by will-ww** [comment]
好，有道理！今天讨论下，我们就开始做起来~
