### ISSUE TITLE
首次打开课程页面无法正常加载。

### ISSUE THREAD

**Issue by bifenglin** [kfcoding/gitcourse#46]
### Describe the bug

首次打开gitcourse页面，无法正常加载出来。

### Did you try recovering your dependencies?

Yes

### Environment

chrome 浏览器

### Steps to reproduce

(Write your steps here:)

1. 打开页面

### Expected behavior

页面可以正常显示

### Actual behavior

一直加载提示

### Reproducible demo

[http://gitcourse.kfcoding.com/#https://code.kfcoding.com/ecnu/the-craft-of-selfteaching.git](http://gitcourse.kfcoding.com/#https://code.kfcoding.com/ecnu/the-craft-of-selfteaching.git)

### Failure Logs
```
code.kfcoding.com:8081/code.kfcoding.com/ecnu/the-craft-of-selfteaching.git/info/refs?service=git-upload-pack:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
index.js:36 Uncaught (in promise) TypeError: Failed to fetch
```

(Please include any relevant log snippets or files here.)

**Comment by will-ww** [comment]
你用的是机器人的模板吗？ @bifenglin

**Comment by willtongji** [comment]
你这个提的地方不对呀？怎么会是GitCourse项目呢？应该在Gitlab上呀~ 捉急~   :-(

**Comment by will-ww** [comment]
你确定是GitCourse项目的问题吗？ @bifenglin

**Comment by LiuChangFreeman** [comment]
> 你确定是GitCourse项目的问题吗？ @bifenglin

这个bug比较复杂

**Comment by bifenglin** [comment]
> 你用的是机器人的模板吗？ @bifenglin

是用的github模板。不是机器人模板。具体使用方式如下[https://help.github.com/cn/enterprise/2.18/user/building-a-strong-community/configuring-issue-templates-for-your-repository](https://help.github.com/cn/enterprise/2.18/user/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by bifenglin** [comment]
> 你确定是GitCourse项目的问题吗？ @bifenglin

确定是gitcourse问题。这个问题不好复现。只能从首次浏览器打开gitcourse页面才能复现。需要慢慢排查问题。

**Comment by will-ww** [comment]
好，这个问题很重要，希望刘畅能够解决掉~ @LiuChangFreeman

**Comment by kitewu** [comment]
cors 服务换了台主机，我这边没问题了，大家可以测一下，一个简单的测试方法是 fork 一门课程到自己的账号下面，然后直接用 gitcourse 打开这门课程。

**Comment by frank-zsy** [comment]
Python 课程我这边可以打开了

**Comment by will-ww** [comment]
我这边也正常了~

**Comment by bifenglin** [comment]
我这边还不能正常打开，依旧报错。没有清空过缓存等相关操作。首次打开。Mac操作系统，Chrome浏览器。
![image](https://user-images.githubusercontent.com/15813364/70592432-c350d680-1c14-11ea-8dfb-0cd712446a88.png)

**Comment by LiuChangFreeman** [comment]
> 我这边还不能正常打开，依旧报错。没有清空过缓存等相关操作。首次打开。Mac操作系统，Chrome浏览器。
> ![image](https://user-images.githubusercontent.com/15813364/70592432-c350d680-1c14-11ea-8dfb-0cd712446a88.png)

彻底将站点数据完全清除，可以解决这个问题

**Comment by bifenglin** [comment]
这个问题出现就是首次打开gitcourse出现，清空缓存就会没问题。所以最好在找一个没有清空过缓存并且首次打开的机器测试一下。我在虚拟机上测试结果。
![image](https://user-images.githubusercontent.com/15813364/70592912-3c046280-1c16-11ea-952b-19cc6b35e975.png)
所以不好复现。而且不好排查错误。

**Comment by bifenglin** [comment]
刚才的错误应该是浏览器兼容问题。换个浏览器应该没问题了，此问题解决。
