### ISSUE TITLE
按照README部署后访问提示"课程拉取失败，请清除缓存后重试"

### ISSUE THREAD

**Issue by PudgeXD** [kfcoding/gitcourse#48]
已确定清理过缓存，
环境：win10 Centos(WSL) x86-64 Linux 4.4.0-17763-Microsoft
请问输出日志可以在什么地方找到？

**Comment by LiuChangFreeman** [comment]
在浏览器开发者控制台
![TIM截图20191224173309](https://user-images.githubusercontent.com/20047907/71406540-7f79ba80-2673-11ea-82ee-104c08bd854f.png)
